version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore (deps) pip"
    ignore:
      - dependency-name: "urllib3"
