name: Create new release

on:
  push:
    branches:
      - main

jobs:
  quality:
    name: Run project test set
    uses: ./.github/workflows/python-tests.yml
    with:
      target_workflow: ./.github/workflows/python-tests.yml

  release:
    needs: quality
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Check triggered by new release
        run: |
          if [[ ${{ github.event.head_commit.message }} =~ ^\d+\.\d+\.\d+ ]]; then
            echo "Workflow triggered by new realease"
          else
            echo "Commit message does not match pattern"
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run:
          pip install -r requirements.txt

      - name: Python Semantic Release
        if: ${{ ! startsWith(github.event.head_commit.message, '[0-9]+.[0-9]+.[0-9]+') }}
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
